In [1]:
import numpy as np



In [17]:
a = [12.23, 13.32, 100, 36.32]

arr = np.array(a)
print(arr)

[ 12.23  13.32 100.    36.32]


In [16]:
arr1 = np.arange(2, 11).reshape(3, 3)
print(arr1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [15]:
arr2 = np.zeros(10)
arr2[5] = 11
print(arr2)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [14]:
arr3 = np.arange(12, 38)
print(arr3)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [10]:
arr5 = np.arange(1, 5)

float_arr5 = arr5.astype(float)
float_arr5

array([1., 2., 3., 4.])

In [11]:
def celsius_to_fahrenheit(celsius_values):
    celsius_array = np.array(celsius_values, dtype = float)
    fahrenheit_array = celsius_array * (9/5) + 32
    return fahrenheit_array

def fahrenheit_to_celsius(fahrenheit_values):
    fahrenheit_array = np.array(fahrenheit_values, dtype=float)
    celsius_array = (fahrenheit_array - 32)* (5/9)
    return celsius_array

centigrade_input_1 = np.array([0, 12, 45.21, 34, 99.91])
print("--- Centigrade to Fahrenheit Conversion ---")
print(f"Original Centigrade values: {centigrade_input_1}")
fahrenheit_output_1 = celsius_to_fahrenheit(centigrade_input_1)
print(f"Values in Fahrenheit degrees: {fahrenheit_output_1}\n")
fahrenheit_input_2 = np.array([0., 12., 45.21, 34., 99.91, 32.])

print("--- Fahrenheit to Centigrade Conversion ---")
print(f"Original Fahrenheit values: {fahrenheit_input_2}")

centigrade_output_2 = fahrenheit_to_celsius(fahrenheit_input_2)
# Rounding to two decimal places to match the sample output's precision
print(f"Values in Centigrade degrees: {np.round(centigrade_output_2, 2)}")





    

--- Centigrade to Fahrenheit Conversion ---
Original Centigrade values: [ 0.   12.   45.21 34.   99.91]
Values in Fahrenheit degrees: [ 32.     53.6   113.378  93.2   211.838]

--- Fahrenheit to Centigrade Conversion ---
Original Fahrenheit values: [ 0.   12.   45.21 34.   99.91 32.  ]
Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73   0.  ]


In [13]:
original_array = np.array([10, 20, 30])
print("Original array: ")
print(original_array)

#Values to append

values_to_append = np.array([40, 50, 60, 70, 80, 90])

appended_array = np.append(original_array, values_to_append)

print("\nAfter append values to the end of the array: ")

print(appended_array)

Original array: 
[10 20 30]

After append values to the end of the array: 
[10 20 30 40 50 60 70 80 90]


In [21]:
import statistics
import random
statis_arr = np.random.randint(1, 100, size = 10)
statis_arr

mean_statis_arr = statistics.mean(statis_arr)
print(f"mean of array {mean_statis_arr}")

median_statis_arr = statistics.median(statis_arr)

print(f'meadian of array {median_statis_arr}')

std_statis_arr = np.std(statis_arr)

print(f"Standart Deviation: ", std_statis_arr)




mean of array 61
meadian of array 62.0
Standart Deviation:  23.562682360037027


In [27]:
new_arr = np.random.randint(1, 1000, size = (10, 10))

new_arr

max_new_arr = np.amax(new_arr)
print(f"max value {max_new_arr}")
min_new_arr = np.amin(new_arr)

print(f"min value {min_new_arr}")

max value 990
min value 8


In [29]:
random_arr = np.random.randint(1, 1000, size = (3, 3, 3))
print(random_arr)

[[[309 553 110]
  [119  69 959]
  [272 818 855]]

 [[361 857 671]
  [588 654 369]
  [437 929 259]]

 [[607 742 713]
  [546 151 340]
  [403  15  62]]]
